import type { Airport } from "./airport-types"

/**
 * Comprehensive airport database for typeahead search.
 * ~600 airports covering every major hub, popular destination, and award-travel route worldwide.
 */
export const AIRPORTS: readonly Airport[] = [
  // ─── United States ──────────────────────────────────────────────
  { iata: "ABQ", name: "Albuquerque Intl Sunport", city: "Albuquerque", country: "US" },
  { iata: "ALB", name: "Albany Intl", city: "Albany", country: "US" },
  { iata: "ANC", name: "Ted Stevens Anchorage", city: "Anchorage", country: "US", keywords: ["Alaska"] },
  { iata: "ASE", name: "Aspen/Pitkin County", city: "Aspen", country: "US", keywords: ["Colorado"] },
  { iata: "ATL", name: "Hartsfield-Jackson", city: "Atlanta", country: "US" },
  { iata: "AUS", name: "Austin-Bergstrom", city: "Austin", country: "US" },
  { iata: "AVL", name: "Asheville Regional", city: "Asheville", country: "US" },
  { iata: "BDL", name: "Bradley Intl", city: "Hartford", country: "US", keywords: ["Connecticut"] },
  { iata: "BHM", name: "Birmingham-Shuttlesworth", city: "Birmingham", country: "US", keywords: ["Alabama"] },
  { iata: "BNA", name: "Nashville Intl", city: "Nashville", country: "US" },
  { iata: "BOI", name: "Boise Airport", city: "Boise", country: "US" },
  { iata: "BOS", name: "Logan Intl", city: "Boston", country: "US" },
  { iata: "BTV", name: "Burlington Intl", city: "Burlington", country: "US", keywords: ["Vermont"] },
  { iata: "BUF", name: "Buffalo Niagara", city: "Buffalo", country: "US" },
  { iata: "BUR", name: "Hollywood Burbank", city: "Burbank", country: "US", keywords: ["Los Angeles"] },
  { iata: "BWI", name: "Baltimore/Washington", city: "Baltimore", country: "US", keywords: ["Washington"] },
  { iata: "BZN", name: "Bozeman Yellowstone", city: "Bozeman", country: "US", keywords: ["Montana", "Yellowstone"] },
  { iata: "CHS", name: "Charleston Intl", city: "Charleston", country: "US" },
  { iata: "CLE", name: "Cleveland Hopkins", city: "Cleveland", country: "US" },
  { iata: "CLT", name: "Charlotte Douglas", city: "Charlotte", country: "US" },
  { iata: "CMH", name: "John Glenn Columbus", city: "Columbus", country: "US" },
  { iata: "COS", name: "Colorado Springs", city: "Colorado Springs", country: "US" },
  { iata: "CVG", name: "Cincinnati/Northern Kentucky", city: "Cincinnati", country: "US" },
  { iata: "DAL", name: "Dallas Love Field", city: "Dallas", country: "US" },
  { iata: "DAY", name: "James M. Cox Dayton", city: "Dayton", country: "US" },
  { iata: "DCA", name: "Reagan National", city: "Washington", country: "US", keywords: ["DC", "Arlington"] },
  { iata: "DEN", name: "Denver Intl", city: "Denver", country: "US" },
  { iata: "DFW", name: "Dallas/Fort Worth", city: "Dallas", country: "US", keywords: ["Fort Worth"] },
  { iata: "DSM", name: "Des Moines Intl", city: "Des Moines", country: "US" },
  { iata: "DTW", name: "Detroit Metro Wayne", city: "Detroit", country: "US" },
  { iata: "EGE", name: "Eagle County Regional", city: "Vail", country: "US", keywords: ["Eagle", "Beaver Creek"] },
  { iata: "ELP", name: "El Paso Intl", city: "El Paso", country: "US" },
  { iata: "EWR", name: "Newark Liberty", city: "Newark", country: "US", keywords: ["New York"] },
  { iata: "FAI", name: "Fairbanks Intl", city: "Fairbanks", country: "US", keywords: ["Alaska"] },
  { iata: "FAT", name: "Fresno Yosemite", city: "Fresno", country: "US" },
  { iata: "FLL", name: "Fort Lauderdale-Hollywood", city: "Fort Lauderdale", country: "US", keywords: ["Miami"] },
  { iata: "FSD", name: "Sioux Falls Regional", city: "Sioux Falls", country: "US" },
  { iata: "GEG", name: "Spokane Intl", city: "Spokane", country: "US" },
  { iata: "GRR", name: "Gerald R. Ford", city: "Grand Rapids", country: "US" },
  { iata: "GSP", name: "Greenville-Spartanburg", city: "Greenville", country: "US" },
  { iata: "HNL", name: "Daniel K. Inouye", city: "Honolulu", country: "US", keywords: ["Hawaii", "Oahu"] },
  { iata: "HOU", name: "William P. Hobby", city: "Houston", country: "US" },
  { iata: "HSV", name: "Huntsville Intl", city: "Huntsville", country: "US", keywords: ["Alabama"] },
  { iata: "IAD", name: "Dulles Intl", city: "Washington", country: "US", keywords: ["DC", "Dulles"] },
  { iata: "IAH", name: "George Bush Intercontinental", city: "Houston", country: "US" },
  { iata: "ICT", name: "Wichita Eisenhower", city: "Wichita", country: "US" },
  { iata: "IND", name: "Indianapolis Intl", city: "Indianapolis", country: "US" },
  { iata: "JAC", name: "Jackson Hole Airport", city: "Jackson Hole", country: "US", keywords: ["Wyoming", "Grand Teton"] },
  { iata: "JAX", name: "Jacksonville Intl", city: "Jacksonville", country: "US" },
  { iata: "JFK", name: "John F. Kennedy", city: "New York", country: "US", keywords: ["NYC"] },
  { iata: "KOA", name: "Ellison Onizuka Kona", city: "Kona", country: "US", keywords: ["Hawaii", "Big Island"] },
  { iata: "LAS", name: "Harry Reid Intl", city: "Las Vegas", country: "US", keywords: ["Vegas"] },
  { iata: "LAX", name: "Los Angeles Intl", city: "Los Angeles", country: "US", keywords: ["LA"] },
  { iata: "LEX", name: "Blue Grass Airport", city: "Lexington", country: "US", keywords: ["Kentucky"] },
  { iata: "LGA", name: "LaGuardia", city: "New York", country: "US", keywords: ["NYC"] },
  { iata: "LGB", name: "Long Beach", city: "Long Beach", country: "US", keywords: ["Los Angeles"] },
  { iata: "LIH", name: "Lihue Airport", city: "Lihue", country: "US", keywords: ["Hawaii", "Kauai"] },
  { iata: "LIT", name: "Clinton National", city: "Little Rock", country: "US", keywords: ["Arkansas"] },
  { iata: "MCI", name: "Kansas City Intl", city: "Kansas City", country: "US" },
  { iata: "MCO", name: "Orlando Intl", city: "Orlando", country: "US", keywords: ["Disney"] },
  { iata: "MDW", name: "Midway Intl", city: "Chicago", country: "US" },
  { iata: "MEM", name: "Memphis Intl", city: "Memphis", country: "US" },
  { iata: "MHT", name: "Manchester-Boston Regional", city: "Manchester", country: "US", keywords: ["New Hampshire"] },
  { iata: "MIA", name: "Miami Intl", city: "Miami", country: "US" },
  { iata: "MKE", name: "Milwaukee Mitchell", city: "Milwaukee", country: "US" },
  { iata: "MSN", name: "Dane County Regional", city: "Madison", country: "US" },
  { iata: "MSO", name: "Missoula Montana", city: "Missoula", country: "US", keywords: ["Montana", "Glacier"] },
  { iata: "MSP", name: "Minneapolis-Saint Paul", city: "Minneapolis", country: "US", keywords: ["Saint Paul"] },
  { iata: "MSY", name: "Louis Armstrong", city: "New Orleans", country: "US", keywords: ["NOLA"] },
  { iata: "MYR", name: "Myrtle Beach Intl", city: "Myrtle Beach", country: "US" },
  { iata: "OAK", name: "Oakland Intl", city: "Oakland", country: "US", keywords: ["San Francisco", "Bay Area"] },
  { iata: "OGG", name: "Kahului", city: "Maui", country: "US", keywords: ["Hawaii"] },
  { iata: "OKC", name: "Will Rogers World", city: "Oklahoma City", country: "US" },
  { iata: "OMA", name: "Eppley Airfield", city: "Omaha", country: "US" },
  { iata: "ONT", name: "Ontario Intl", city: "Ontario", country: "US", keywords: ["Los Angeles", "Inland Empire"] },
  { iata: "ORD", name: "O'Hare Intl", city: "Chicago", country: "US" },
  { iata: "ORF", name: "Norfolk Intl", city: "Norfolk", country: "US", keywords: ["Virginia Beach"] },
  { iata: "PBI", name: "Palm Beach Intl", city: "West Palm Beach", country: "US" },
  { iata: "PDX", name: "Portland Intl", city: "Portland", country: "US", keywords: ["Oregon"] },
  { iata: "PHL", name: "Philadelphia Intl", city: "Philadelphia", country: "US" },
  { iata: "PHX", name: "Phoenix Sky Harbor", city: "Phoenix", country: "US" },
  { iata: "PIT", name: "Pittsburgh Intl", city: "Pittsburgh", country: "US" },
  { iata: "PNS", name: "Pensacola Intl", city: "Pensacola", country: "US", keywords: ["Florida Panhandle"] },
  { iata: "PSP", name: "Palm Springs Intl", city: "Palm Springs", country: "US" },
  { iata: "PVD", name: "T.F. Green", city: "Providence", country: "US", keywords: ["Rhode Island"] },
  { iata: "PWM", name: "Portland Intl Jetport", city: "Portland", country: "US", keywords: ["Maine"] },
  { iata: "RDU", name: "Raleigh-Durham", city: "Raleigh", country: "US", keywords: ["Durham"] },
  { iata: "RIC", name: "Richmond Intl", city: "Richmond", country: "US" },
  { iata: "RNO", name: "Reno-Tahoe", city: "Reno", country: "US" },
  { iata: "ROC", name: "Greater Rochester", city: "Rochester", country: "US" },
  { iata: "RSW", name: "Southwest Florida", city: "Fort Myers", country: "US" },
  { iata: "SAN", name: "San Diego Intl", city: "San Diego", country: "US" },
  { iata: "SAT", name: "San Antonio Intl", city: "San Antonio", country: "US" },
  { iata: "SAV", name: "Savannah/Hilton Head", city: "Savannah", country: "US" },
  { iata: "SBA", name: "Santa Barbara Airport", city: "Santa Barbara", country: "US" },
  { iata: "SDF", name: "Louisville Muhammad Ali", city: "Louisville", country: "US" },
  { iata: "SEA", name: "Seattle-Tacoma", city: "Seattle", country: "US", keywords: ["Tacoma"] },
  { iata: "SFO", name: "San Francisco Intl", city: "San Francisco", country: "US" },
  { iata: "SJC", name: "San Jose Intl", city: "San Jose", country: "US", keywords: ["Silicon Valley"] },
  { iata: "SLC", name: "Salt Lake City Intl", city: "Salt Lake City", country: "US" },
  { iata: "SMF", name: "Sacramento Intl", city: "Sacramento", country: "US" },
  { iata: "SNA", name: "John Wayne", city: "Santa Ana", country: "US", keywords: ["Orange County", "Los Angeles"] },
  { iata: "SRQ", name: "Sarasota-Bradenton", city: "Sarasota", country: "US" },
  { iata: "STL", name: "St. Louis Lambert", city: "St. Louis", country: "US" },
  { iata: "SYR", name: "Syracuse Hancock", city: "Syracuse", country: "US" },
  { iata: "TPA", name: "Tampa Intl", city: "Tampa", country: "US" },
  { iata: "TUL", name: "Tulsa Intl", city: "Tulsa", country: "US" },
  { iata: "TUS", name: "Tucson Intl", city: "Tucson", country: "US" },
  { iata: "TYS", name: "McGhee Tyson", city: "Knoxville", country: "US" },
  { iata: "EYW", name: "Key West Intl", city: "Key West", country: "US", keywords: ["Florida Keys"] },
  { iata: "XNA", name: "Northwest Arkansas Regional", city: "Fayetteville", country: "US", keywords: ["Bentonville", "Arkansas"] },

  // ─── Canada ─────────────────────────────────────────────────────
  { iata: "YEG", name: "Edmonton Intl", city: "Edmonton", country: "Canada" },
  { iata: "YHZ", name: "Halifax Stanfield", city: "Halifax", country: "Canada" },
  { iata: "YKA", name: "Kamloops Airport", city: "Kamloops", country: "Canada" },
  { iata: "YKF", name: "Region of Waterloo", city: "Kitchener", country: "Canada", keywords: ["Waterloo"] },
  { iata: "YOW", name: "Ottawa Macdonald-Cartier", city: "Ottawa", country: "Canada" },
  { iata: "YQB", name: "Jean Lesage", city: "Quebec City", country: "Canada" },
  { iata: "YQR", name: "Regina Intl", city: "Regina", country: "Canada" },
  { iata: "YSJ", name: "Saint John Airport", city: "Saint John", country: "Canada", keywords: ["New Brunswick"] },
  { iata: "YUL", name: "Montréal-Trudeau", city: "Montreal", country: "Canada", keywords: ["Montréal"] },
  { iata: "YVR", name: "Vancouver Intl", city: "Vancouver", country: "Canada" },
  { iata: "YWG", name: "Winnipeg Richardson", city: "Winnipeg", country: "Canada" },
  { iata: "YXE", name: "Saskatoon John G. Diefenbaker", city: "Saskatoon", country: "Canada" },
  { iata: "YYC", name: "Calgary Intl", city: "Calgary", country: "Canada" },
  { iata: "YLW", name: "Kelowna Intl", city: "Kelowna", country: "Canada", keywords: ["Okanagan"] },
  { iata: "YXU", name: "London Intl", city: "London", country: "Canada", keywords: ["Ontario"] },
  { iata: "YYJ", name: "Victoria Intl", city: "Victoria", country: "Canada", keywords: ["British Columbia"] },
  { iata: "YYT", name: "St. John's Intl", city: "St. John's", country: "Canada", keywords: ["Newfoundland"] },
  { iata: "YYZ", name: "Toronto Pearson", city: "Toronto", country: "Canada" },

  // ─── Mexico ─────────────────────────────────────────────────────
  { iata: "ACA", name: "General Juan N. Álvarez", city: "Acapulco", country: "Mexico" },
  { iata: "BJX", name: "Del Bajío", city: "León", country: "Mexico", keywords: ["Guanajuato"] },
  { iata: "CUN", name: "Cancún Intl", city: "Cancún", country: "Mexico", keywords: ["Cancun"] },
  { iata: "CZM", name: "Cozumel Intl", city: "Cozumel", country: "Mexico" },
  { iata: "GDL", name: "Guadalajara Intl", city: "Guadalajara", country: "Mexico" },
  { iata: "HMO", name: "General Ignacio Pesqueira García", city: "Hermosillo", country: "Mexico" },
  { iata: "HUX", name: "Bahías de Huatulco", city: "Huatulco", country: "Mexico" },
  { iata: "MEX", name: "Benito Juárez", city: "Mexico City", country: "Mexico", keywords: ["CDMX"] },
  { iata: "MID", name: "Mérida Intl", city: "Mérida", country: "Mexico", keywords: ["Yucatán"] },
  { iata: "MTY", name: "Monterrey Intl", city: "Monterrey", country: "Mexico" },
  { iata: "OAX", name: "Xoxocotlán", city: "Oaxaca", country: "Mexico" },
  { iata: "PVR", name: "Gustavo Díaz Ordaz", city: "Puerto Vallarta", country: "Mexico" },
  { iata: "QRO", name: "Querétaro Intl", city: "Querétaro", country: "Mexico" },
  { iata: "SJD", name: "Los Cabos", city: "San José del Cabo", country: "Mexico", keywords: ["Cabo"] },
  { iata: "TIJ", name: "General Abelardo L. Rodríguez", city: "Tijuana", country: "Mexico" },
  { iata: "ZIH", name: "Ixtapa-Zihuatanejo", city: "Ixtapa", country: "Mexico" },
  { iata: "ZLO", name: "Playa de Oro", city: "Manzanillo", country: "Mexico" },

  // ─── Caribbean ──────────────────────────────────────────────────
  { iata: "ANU", name: "V.C. Bird", city: "St. John's", country: "Antigua & Barbuda" },
  { iata: "AUA", name: "Queen Beatrix", city: "Oranjestad", country: "Aruba" },
  { iata: "BGI", name: "Grantley Adams", city: "Bridgetown", country: "Barbados" },
  { iata: "BON", name: "Flamingo Intl", city: "Kralendijk", country: "Bonaire" },
  { iata: "CUR", name: "Hato Intl", city: "Willemstad", country: "Curaçao" },
  { iata: "FDF", name: "Aimé Césaire", city: "Fort-de-France", country: "Martinique" },
  { iata: "GCM", name: "Owen Roberts", city: "Grand Cayman", country: "Cayman Islands" },
  { iata: "GND", name: "Maurice Bishop", city: "St. George's", country: "Grenada" },
  { iata: "HAV", name: "José Martí", city: "Havana", country: "Cuba" },
  { iata: "KIN", name: "Norman Manley", city: "Kingston", country: "Jamaica" },
  { iata: "MBJ", name: "Sangster Intl", city: "Montego Bay", country: "Jamaica" },
  { iata: "NAS", name: "Lynden Pindling", city: "Nassau", country: "Bahamas" },
  { iata: "PAP", name: "Toussaint Louverture", city: "Port-au-Prince", country: "Haiti" },
  { iata: "PLS", name: "Providenciales Intl", city: "Providenciales", country: "Turks & Caicos" },
  { iata: "POS", name: "Piarco Intl", city: "Port of Spain", country: "Trinidad & Tobago" },
  { iata: "PTP", name: "Pôle Caraïbes", city: "Pointe-à-Pitre", country: "Guadeloupe" },
  { iata: "POP", name: "Gregorio Luperón", city: "Puerto Plata", country: "Dominican Republic" },
  { iata: "PUJ", name: "Punta Cana Intl", city: "Punta Cana", country: "Dominican Republic" },
  { iata: "SDQ", name: "Las Américas", city: "Santo Domingo", country: "Dominican Republic" },
  { iata: "SJU", name: "Luis Muñoz Marín", city: "San Juan", country: "Puerto Rico" },
  { iata: "SKB", name: "Robert L. Bradshaw", city: "Basseterre", country: "St. Kitts & Nevis" },
  { iata: "STT", name: "Cyril E. King", city: "St. Thomas", country: "US Virgin Islands" },
  { iata: "STX", name: "Henry E. Rohlsen", city: "St. Croix", country: "US Virgin Islands" },
  { iata: "SXM", name: "Princess Juliana", city: "Sint Maarten", country: "Sint Maarten" },
  { iata: "TAB", name: "A.N.R. Robinson", city: "Tobago", country: "Trinidad & Tobago" },
  { iata: "UVF", name: "Hewanorra Intl", city: "Vieux Fort", country: "St. Lucia" },
  { iata: "BDA", name: "L.F. Wade Intl", city: "Hamilton", country: "Bermuda" },
  { iata: "EIS", name: "Terrance B. Lettsome", city: "Tortola", country: "British Virgin Islands", keywords: ["BVI"] },

  // ─── Central America ──────────────────────────────────────────
  { iata: "BZE", name: "Philip Goldson", city: "Belize City", country: "Belize" },
  { iata: "GUA", name: "La Aurora", city: "Guatemala City", country: "Guatemala" },
  { iata: "LIR", name: "Daniel Oduber Quirós", city: "Liberia", country: "Costa Rica", keywords: ["Guanacaste"] },
  { iata: "MGA", name: "Augusto C. Sandino", city: "Managua", country: "Nicaragua" },
  { iata: "PTY", name: "Tocumen Intl", city: "Panama City", country: "Panama" },
  { iata: "RTB", name: "Juan Manuel Gálvez", city: "Roatán", country: "Honduras" },
  { iata: "SAL", name: "Óscar Arnulfo Romero", city: "San Salvador", country: "El Salvador" },
  { iata: "SAP", name: "Ramón Villeda Morales", city: "San Pedro Sula", country: "Honduras" },
  { iata: "SJO", name: "Juan Santamaría", city: "San José", country: "Costa Rica" },
  { iata: "TGU", name: "Toncontín", city: "Tegucigalpa", country: "Honduras" },

  // ─── South America ──────────────────────────────────────────────
  { iata: "AEP", name: "Aeroparque Jorge Newbery", city: "Buenos Aires", country: "Argentina" },
  { iata: "ASU", name: "Silvio Pettirossi", city: "Asunción", country: "Paraguay" },
  { iata: "BOG", name: "El Dorado", city: "Bogotá", country: "Colombia", keywords: ["Bogota"] },
  { iata: "BSB", name: "Presidente Juscelino", city: "Brasília", country: "Brazil" },
  { iata: "CCS", name: "Simón Bolívar", city: "Caracas", country: "Venezuela" },
  { iata: "CLO", name: "Alfonso Bonilla Aragón", city: "Cali", country: "Colombia" },
  { iata: "CNF", name: "Confins", city: "Belo Horizonte", country: "Brazil" },
  { iata: "COR", name: "Ingeniero Taravella", city: "Córdoba", country: "Argentina" },
  { iata: "CTG", name: "Rafael Núñez", city: "Cartagena", country: "Colombia" },
  { iata: "CWB", name: "Afonso Pena", city: "Curitiba", country: "Brazil" },
  { iata: "EZE", name: "Ministro Pistarini", city: "Buenos Aires", country: "Argentina", keywords: ["Ezeiza"] },
  { iata: "FLN", name: "Hercílio Luz", city: "Florianópolis", country: "Brazil" },
  { iata: "FOR", name: "Pinto Martins", city: "Fortaleza", country: "Brazil" },
  { iata: "GIG", name: "Galeão", city: "Rio de Janeiro", country: "Brazil" },
  { iata: "GPS", name: "Seymour", city: "Baltra", country: "Ecuador", keywords: ["Galápagos"] },
  { iata: "GRU", name: "Guarulhos", city: "São Paulo", country: "Brazil", keywords: ["Sao Paulo"] },
  { iata: "GYE", name: "José Joaquín de Olmedo", city: "Guayaquil", country: "Ecuador" },
  { iata: "IGR", name: "Cataratas del Iguazú", city: "Iguazú", country: "Argentina", keywords: ["Iguazu Falls"] },
  { iata: "CUZ", name: "Alejandro Velasco Astete", city: "Cusco", country: "Peru", keywords: ["Machu Picchu"] },
  { iata: "LIM", name: "Jorge Chávez", city: "Lima", country: "Peru" },
  { iata: "LPB", name: "El Alto", city: "La Paz", country: "Bolivia" },
  { iata: "MDE", name: "José María Córdova", city: "Medellín", country: "Colombia", keywords: ["Medellin"] },
  { iata: "MVD", name: "Carrasco Intl", city: "Montevideo", country: "Uruguay" },
  { iata: "NAT", name: "São Gonçalo do Amarante", city: "Natal", country: "Brazil" },
  { iata: "POA", name: "Salgado Filho", city: "Porto Alegre", country: "Brazil" },
  { iata: "REC", name: "Guararapes", city: "Recife", country: "Brazil" },
  { iata: "SCL", name: "Arturo Merino Benítez", city: "Santiago", country: "Chile" },
  { iata: "SDU", name: "Santos Dumont", city: "Rio de Janeiro", country: "Brazil" },
  { iata: "SSA", name: "Deputado Luís Eduardo Magalhães", city: "Salvador", country: "Brazil" },
  { iata: "UIO", name: "Mariscal Sucre", city: "Quito", country: "Ecuador" },
  { iata: "VVI", name: "Viru Viru", city: "Santa Cruz", country: "Bolivia" },

  // ─── United Kingdom & Ireland ───────────────────────────────────
  { iata: "ABZ", name: "Aberdeen Airport", city: "Aberdeen", country: "UK", keywords: ["Scotland"] },
  { iata: "BFS", name: "Belfast Intl", city: "Belfast", country: "UK", keywords: ["Northern Ireland"] },
  { iata: "BHX", name: "Birmingham Airport", city: "Birmingham", country: "UK" },
  { iata: "BRS", name: "Bristol Airport", city: "Bristol", country: "UK" },
  { iata: "CWL", name: "Cardiff Airport", city: "Cardiff", country: "UK", keywords: ["Wales"] },
  { iata: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland" },
  { iata: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "UK", keywords: ["Scotland"] },
  { iata: "EMA", name: "East Midlands", city: "Nottingham", country: "UK" },
  { iata: "GLA", name: "Glasgow Airport", city: "Glasgow", country: "UK", keywords: ["Scotland"] },
  { iata: "JER", name: "Jersey Airport", city: "Jersey", country: "UK", keywords: ["Channel Islands"] },
  { iata: "KNO", name: "Knock Ireland West", city: "Knock", country: "Ireland", keywords: ["Ireland West"] },
  { iata: "LBA", name: "Leeds Bradford", city: "Leeds", country: "UK" },
  { iata: "LGW", name: "Gatwick", city: "London", country: "UK" },
  { iata: "LHR", name: "Heathrow", city: "London", country: "UK" },
  { iata: "LPL", name: "Liverpool John Lennon", city: "Liverpool", country: "UK" },
  { iata: "LTN", name: "Luton Airport", city: "London", country: "UK" },
  { iata: "MAN", name: "Manchester Airport", city: "Manchester", country: "UK" },
  { iata: "NCL", name: "Newcastle Airport", city: "Newcastle", country: "UK" },
  { iata: "ORK", name: "Cork Airport", city: "Cork", country: "Ireland" },
  { iata: "SNN", name: "Shannon Airport", city: "Shannon", country: "Ireland" },
  { iata: "SOU", name: "Southampton Airport", city: "Southampton", country: "UK" },
  { iata: "STN", name: "Stansted", city: "London", country: "UK" },

  // ─── France ─────────────────────────────────────────────────────
  { iata: "AJA", name: "Campo dell'Oro", city: "Ajaccio", country: "France", keywords: ["Corsica"] },
  { iata: "BIA", name: "Poretta", city: "Bastia", country: "France", keywords: ["Corsica"] },
  { iata: "BIQ", name: "Pays Basque", city: "Biarritz", country: "France" },
  { iata: "BOD", name: "Bordeaux-Mérignac", city: "Bordeaux", country: "France" },
  { iata: "CDG", name: "Charles de Gaulle", city: "Paris", country: "France" },
  { iata: "LIL", name: "Lille Airport", city: "Lille", country: "France" },
  { iata: "LYS", name: "Lyon-Saint Exupéry", city: "Lyon", country: "France" },
  { iata: "MPL", name: "Montpellier-Méditerranée", city: "Montpellier", country: "France" },
  { iata: "MRS", name: "Marseille Provence", city: "Marseille", country: "France" },
  { iata: "NCE", name: "Côte d'Azur", city: "Nice", country: "France" },
  { iata: "NTE", name: "Nantes Atlantique", city: "Nantes", country: "France" },
  { iata: "ORY", name: "Orly", city: "Paris", country: "France" },
  { iata: "RNS", name: "Rennes-Saint-Jacques", city: "Rennes", country: "France" },
  { iata: "SXB", name: "Strasbourg Airport", city: "Strasbourg", country: "France" },
  { iata: "TLS", name: "Toulouse-Blagnac", city: "Toulouse", country: "France" },

  // ─── Germany ────────────────────────────────────────────────────
  { iata: "BER", name: "Berlin Brandenburg", city: "Berlin", country: "Germany" },
  { iata: "BRE", name: "Bremen Airport", city: "Bremen", country: "Germany" },
  { iata: "CGN", name: "Cologne Bonn", city: "Cologne", country: "Germany", keywords: ["Köln"] },
  { iata: "DTM", name: "Dortmund Airport", city: "Dortmund", country: "Germany" },
  { iata: "DUS", name: "Düsseldorf Airport", city: "Düsseldorf", country: "Germany", keywords: ["Dusseldorf"] },
  { iata: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany" },
  { iata: "HAJ", name: "Hannover Airport", city: "Hannover", country: "Germany" },
  { iata: "HAM", name: "Hamburg Airport", city: "Hamburg", country: "Germany" },
  { iata: "LEJ", name: "Leipzig/Halle", city: "Leipzig", country: "Germany" },
  { iata: "MUC", name: "Franz Josef Strauss", city: "Munich", country: "Germany", keywords: ["München"] },
  { iata: "NUE", name: "Nuremberg Airport", city: "Nuremberg", country: "Germany", keywords: ["Nürnberg"] },
  { iata: "STR", name: "Stuttgart Airport", city: "Stuttgart", country: "Germany" },

  // ─── Spain ──────────────────────────────────────────────────────
  { iata: "ACE", name: "Lanzarote Airport", city: "Lanzarote", country: "Spain", keywords: ["Canary Islands"] },
  { iata: "AGP", name: "Málaga-Costa del Sol", city: "Málaga", country: "Spain", keywords: ["Malaga"] },
  { iata: "ALC", name: "Alicante-Elche", city: "Alicante", country: "Spain" },
  { iata: "BCN", name: "El Prat", city: "Barcelona", country: "Spain" },
  { iata: "BIO", name: "Bilbao Airport", city: "Bilbao", country: "Spain" },
  { iata: "FUE", name: "Fuerteventura Airport", city: "Fuerteventura", country: "Spain", keywords: ["Canary Islands"] },
  { iata: "GRX", name: "Federico García Lorca", city: "Granada", country: "Spain" },
  { iata: "IBZ", name: "Ibiza Airport", city: "Ibiza", country: "Spain" },
  { iata: "LPA", name: "Gran Canaria", city: "Las Palmas", country: "Spain", keywords: ["Canary Islands"] },
  { iata: "MAD", name: "Barajas", city: "Madrid", country: "Spain" },
  { iata: "MAH", name: "Menorca Airport", city: "Menorca", country: "Spain", keywords: ["Minorca"] },
  { iata: "PMI", name: "Palma de Mallorca", city: "Palma", country: "Spain", keywords: ["Mallorca", "Majorca"] },
  { iata: "SCQ", name: "Santiago de Compostela", city: "Santiago de Compostela", country: "Spain", keywords: ["Galicia"] },
  { iata: "SVQ", name: "San Pablo", city: "Seville", country: "Spain", keywords: ["Sevilla"] },
  { iata: "TFN", name: "Tenerife North", city: "Tenerife", country: "Spain", keywords: ["Canary Islands"] },
  { iata: "TFS", name: "Tenerife South", city: "Tenerife", country: "Spain", keywords: ["Canary Islands"] },
  { iata: "VLC", name: "Valencia Airport", city: "Valencia", country: "Spain" },

  // ─── Italy ──────────────────────────────────────────────────────
  { iata: "BGY", name: "Orio al Serio", city: "Bergamo", country: "Italy", keywords: ["Milan"] },
  { iata: "BLQ", name: "Guglielmo Marconi", city: "Bologna", country: "Italy" },
  { iata: "BRI", name: "Karol Wojtyła", city: "Bari", country: "Italy", keywords: ["Puglia"] },
  { iata: "CAG", name: "Elmas", city: "Cagliari", country: "Italy", keywords: ["Sardinia"] },
  { iata: "CTA", name: "Fontanarossa", city: "Catania", country: "Italy", keywords: ["Sicily"] },
  { iata: "FCO", name: "Fiumicino", city: "Rome", country: "Italy", keywords: ["Roma"] },
  { iata: "FLR", name: "Amerigo Vespucci", city: "Florence", country: "Italy", keywords: ["Firenze"] },
  { iata: "GOA", name: "Cristoforo Colombo", city: "Genoa", country: "Italy", keywords: ["Genova"] },
  { iata: "LIN", name: "Linate", city: "Milan", country: "Italy", keywords: ["Milano"] },
  { iata: "MXP", name: "Malpensa", city: "Milan", country: "Italy", keywords: ["Milano"] },
  { iata: "NAP", name: "Capodichino", city: "Naples", country: "Italy", keywords: ["Napoli"] },
  { iata: "OLB", name: "Costa Smeralda", city: "Olbia", country: "Italy", keywords: ["Sardinia"] },
  { iata: "PMO", name: "Falcone-Borsellino", city: "Palermo", country: "Italy", keywords: ["Sicily"] },
  { iata: "PSA", name: "Galileo Galilei", city: "Pisa", country: "Italy", keywords: ["Tuscany"] },
  { iata: "TRN", name: "Caselle", city: "Turin", country: "Italy", keywords: ["Torino"] },
  { iata: "TRS", name: "Ronchi dei Legionari", city: "Trieste", country: "Italy" },
  { iata: "VCE", name: "Marco Polo", city: "Venice", country: "Italy", keywords: ["Venezia"] },
  { iata: "VRN", name: "Valerio Catullo", city: "Verona", country: "Italy" },

  // ─── Portugal ───────────────────────────────────────────────────
  { iata: "FAO", name: "Faro Airport", city: "Faro", country: "Portugal", keywords: ["Algarve"] },
  { iata: "FNC", name: "Cristiano Ronaldo", city: "Funchal", country: "Portugal", keywords: ["Madeira"] },
  { iata: "LIS", name: "Humberto Delgado", city: "Lisbon", country: "Portugal", keywords: ["Lisboa"] },
  { iata: "OPO", name: "Francisco Sá Carneiro", city: "Porto", country: "Portugal" },
  { iata: "PDL", name: "João Paulo II", city: "Ponta Delgada", country: "Portugal", keywords: ["Azores"] },

  // ─── Benelux ────────────────────────────────────────────────────
  { iata: "AMS", name: "Schiphol", city: "Amsterdam", country: "Netherlands" },
  { iata: "BRU", name: "Brussels Airport", city: "Brussels", country: "Belgium" },
  { iata: "CRL", name: "Brussels South Charleroi", city: "Charleroi", country: "Belgium" },
  { iata: "EIN", name: "Eindhoven Airport", city: "Eindhoven", country: "Netherlands" },
  { iata: "LUX", name: "Luxembourg Airport", city: "Luxembourg", country: "Luxembourg" },
  { iata: "RTM", name: "Rotterdam The Hague", city: "Rotterdam", country: "Netherlands" },

  // ─── Scandinavia ────────────────────────────────────────────────
  { iata: "AAL", name: "Aalborg Airport", city: "Aalborg", country: "Denmark" },
  { iata: "ARN", name: "Arlanda", city: "Stockholm", country: "Sweden" },
  { iata: "BGO", name: "Flesland", city: "Bergen", country: "Norway" },
  { iata: "BLL", name: "Billund Airport", city: "Billund", country: "Denmark" },
  { iata: "CPH", name: "Kastrup", city: "Copenhagen", country: "Denmark" },
  { iata: "GOT", name: "Landvetter", city: "Gothenburg", country: "Sweden" },
  { iata: "HEL", name: "Helsinki-Vantaa", city: "Helsinki", country: "Finland" },
  { iata: "KEF", name: "Keflavík Intl", city: "Reykjavik", country: "Iceland", keywords: ["Reykjavík"] },
  { iata: "MMX", name: "Malmö Airport", city: "Malmö", country: "Sweden" },
  { iata: "OSL", name: "Gardermoen", city: "Oslo", country: "Norway" },
  { iata: "OUL", name: "Oulu Airport", city: "Oulu", country: "Finland" },
  { iata: "RVN", name: "Rovaniemi Airport", city: "Rovaniemi", country: "Finland", keywords: ["Lapland"] },
  { iata: "SVG", name: "Sola", city: "Stavanger", country: "Norway" },
  { iata: "TMP", name: "Pirkkala", city: "Tampere", country: "Finland" },
  { iata: "TOS", name: "Tromsø Airport", city: "Tromsø", country: "Norway", keywords: ["Northern Lights"] },
  { iata: "TRD", name: "Værnes", city: "Trondheim", country: "Norway" },

  // ─── Austria & Switzerland ──────────────────────────────────────
  { iata: "BSL", name: "EuroAirport", city: "Basel", country: "Switzerland", keywords: ["Mulhouse"] },
  { iata: "GRZ", name: "Graz Airport", city: "Graz", country: "Austria" },
  { iata: "GVA", name: "Geneva Airport", city: "Geneva", country: "Switzerland" },
  { iata: "INN", name: "Innsbruck Airport", city: "Innsbruck", country: "Austria", keywords: ["Tyrol"] },
  { iata: "SZG", name: "Salzburg Airport", city: "Salzburg", country: "Austria" },
  { iata: "VIE", name: "Vienna Intl", city: "Vienna", country: "Austria", keywords: ["Wien"] },
  { iata: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland", keywords: ["Zürich"] },

  // ─── Greece ─────────────────────────────────────────────────────
  { iata: "ATH", name: "Eleftherios Venizelos", city: "Athens", country: "Greece" },
  { iata: "CFU", name: "Ioannis Kapodistrias", city: "Corfu", country: "Greece" },
  { iata: "CHQ", name: "Daskalogiannis", city: "Chania", country: "Greece", keywords: ["Crete"] },
  { iata: "HER", name: "Nikos Kazantzakis", city: "Heraklion", country: "Greece", keywords: ["Crete"] },
  { iata: "JMK", name: "Mykonos Airport", city: "Mykonos", country: "Greece" },
  { iata: "JTR", name: "Santorini Airport", city: "Santorini", country: "Greece", keywords: ["Thira"] },
  { iata: "KGS", name: "Hippocrates Intl", city: "Kos", country: "Greece" },
  { iata: "RHO", name: "Diagoras", city: "Rhodes", country: "Greece" },
  { iata: "SKG", name: "Makedonia", city: "Thessaloniki", country: "Greece" },
  { iata: "ZTH", name: "Zakynthos Intl", city: "Zakynthos", country: "Greece", keywords: ["Zante"] },

  // ─── Turkey ─────────────────────────────────────────────────────
  { iata: "ADB", name: "Adnan Menderes", city: "Izmir", country: "Turkey" },
  { iata: "AYT", name: "Antalya Airport", city: "Antalya", country: "Turkey" },
  { iata: "BJV", name: "Milas-Bodrum", city: "Bodrum", country: "Turkey" },
  { iata: "DLM", name: "Dalaman Airport", city: "Dalaman", country: "Turkey", keywords: ["Fethiye", "Ölüdeniz"] },
  { iata: "ESB", name: "Esenboğa", city: "Ankara", country: "Turkey" },
  { iata: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey", keywords: ["Türkiye"] },
  { iata: "SAW", name: "Sabiha Gökçen", city: "Istanbul", country: "Turkey" },
  { iata: "TZX", name: "Trabzon Airport", city: "Trabzon", country: "Turkey" },

  // ─── Eastern Europe & Balkans ─────────────────────────────────
  { iata: "BEG", name: "Nikola Tesla", city: "Belgrade", country: "Serbia" },
  { iata: "BTS", name: "M. R. Štefánik", city: "Bratislava", country: "Slovakia" },
  { iata: "BUD", name: "Budapest Liszt Ferenc", city: "Budapest", country: "Hungary" },
  { iata: "CLJ", name: "Avram Iancu", city: "Cluj-Napoca", country: "Romania" },
  { iata: "DBV", name: "Dubrovnik Airport", city: "Dubrovnik", country: "Croatia" },
  { iata: "GDN", name: "Lech Wałęsa", city: "Gdańsk", country: "Poland", keywords: ["Gdansk"] },
  { iata: "KRK", name: "John Paul II", city: "Kraków", country: "Poland", keywords: ["Krakow"] },
  { iata: "KTW", name: "Pyrzowice", city: "Katowice", country: "Poland" },
  { iata: "LJU", name: "Jože Pučnik", city: "Ljubljana", country: "Slovenia" },
  { iata: "OTP", name: "Henri Coandă", city: "Bucharest", country: "Romania" },
  { iata: "POZ", name: "Ławica", city: "Poznań", country: "Poland", keywords: ["Poznan"] },
  { iata: "PRG", name: "Václav Havel", city: "Prague", country: "Czech Republic", keywords: ["Praha"] },
  { iata: "PRN", name: "Pristina Intl", city: "Pristina", country: "Kosovo" },
  { iata: "PUY", name: "Pula Airport", city: "Pula", country: "Croatia", keywords: ["Istria"] },
  { iata: "RIX", name: "Riga Intl", city: "Riga", country: "Latvia" },
  { iata: "SJJ", name: "Sarajevo Intl", city: "Sarajevo", country: "Bosnia & Herzegovina" },
  { iata: "SKP", name: "Skopje Intl", city: "Skopje", country: "North Macedonia" },
  { iata: "SOF", name: "Sofia Airport", city: "Sofia", country: "Bulgaria" },
  { iata: "SPU", name: "Split Airport", city: "Split", country: "Croatia" },
  { iata: "TGD", name: "Podgorica Airport", city: "Podgorica", country: "Montenegro" },
  { iata: "TIA", name: "Mother Teresa", city: "Tirana", country: "Albania" },
  { iata: "TIV", name: "Tivat Airport", city: "Tivat", country: "Montenegro" },
  { iata: "TLL", name: "Lennart Meri", city: "Tallinn", country: "Estonia" },
  { iata: "TSR", name: "Timișoara Airport", city: "Timișoara", country: "Romania" },
  { iata: "VAR", name: "Varna Airport", city: "Varna", country: "Bulgaria" },
  { iata: "VNO", name: "Vilnius Airport", city: "Vilnius", country: "Lithuania" },
  { iata: "WAW", name: "Chopin Airport", city: "Warsaw", country: "Poland", keywords: ["Warszawa"] },
  { iata: "WRO", name: "Copernicus Airport", city: "Wrocław", country: "Poland", keywords: ["Wroclaw"] },
  { iata: "ZAD", name: "Zadar Airport", city: "Zadar", country: "Croatia" },
  { iata: "ZAG", name: "Franjo Tuđman", city: "Zagreb", country: "Croatia" },

  // ─── Cyprus & Malta ─────────────────────────────────────────────
  { iata: "LCA", name: "Larnaca Intl", city: "Larnaca", country: "Cyprus" },
  { iata: "MLA", name: "Malta Intl", city: "Valletta", country: "Malta" },
  { iata: "PFO", name: "Paphos Intl", city: "Paphos", country: "Cyprus" },

  // ─── Russia & CIS ──────────────────────────────────────────────
  { iata: "AER", name: "Sochi Intl", city: "Sochi", country: "Russia" },
  { iata: "ALA", name: "Almaty Intl", city: "Almaty", country: "Kazakhstan" },
  { iata: "DME", name: "Domodedovo", city: "Moscow", country: "Russia" },
  { iata: "EVN", name: "Zvartnots", city: "Yerevan", country: "Armenia" },
  { iata: "FRU", name: "Manas Intl", city: "Bishkek", country: "Kyrgyzstan" },
  { iata: "GYD", name: "Heydar Aliyev", city: "Baku", country: "Azerbaijan" },
  { iata: "KBP", name: "Boryspil Intl", city: "Kyiv", country: "Ukraine", keywords: ["Kiev"] },
  { iata: "KZN", name: "Kazan Intl", city: "Kazan", country: "Russia" },
  { iata: "LED", name: "Pulkovo", city: "St. Petersburg", country: "Russia" },
  { iata: "NQZ", name: "Nursultan Nazarbayev", city: "Astana", country: "Kazakhstan" },
  { iata: "ODS", name: "Odesa Intl", city: "Odesa", country: "Ukraine" },
  { iata: "OVB", name: "Tolmachevo", city: "Novosibirsk", country: "Russia" },
  { iata: "SVO", name: "Sheremetyevo", city: "Moscow", country: "Russia" },
  { iata: "TAS", name: "Islam Karimov", city: "Tashkent", country: "Uzbekistan" },
  { iata: "TBS", name: "Shota Rustaveli", city: "Tbilisi", country: "Georgia" },
  { iata: "VKO", name: "Vnukovo", city: "Moscow", country: "Russia" },
  { iata: "VVO", name: "Knevichi", city: "Vladivostok", country: "Russia" },
  { iata: "YKS", name: "Yakutsk Airport", city: "Yakutsk", country: "Russia" },

  // ─── Middle East ────────────────────────────────────────────────
  { iata: "AMM", name: "Queen Alia", city: "Amman", country: "Jordan" },
  { iata: "AQJ", name: "King Hussein", city: "Aqaba", country: "Jordan" },
  { iata: "AUH", name: "Zayed Intl", city: "Abu Dhabi", country: "UAE" },
  { iata: "BAH", name: "Bahrain Intl", city: "Manama", country: "Bahrain" },
  { iata: "BEY", name: "Rafic Hariri", city: "Beirut", country: "Lebanon" },
  { iata: "BGW", name: "Baghdad Intl", city: "Baghdad", country: "Iraq" },
  { iata: "DMM", name: "King Fahd", city: "Dammam", country: "Saudi Arabia" },
  { iata: "DOH", name: "Hamad Intl", city: "Doha", country: "Qatar" },
  { iata: "DWC", name: "Al Maktoum Intl", city: "Dubai", country: "UAE", keywords: ["Dubai World Central"] },
  { iata: "DXB", name: "Dubai Intl", city: "Dubai", country: "UAE" },
  { iata: "EBL", name: "Erbil Intl", city: "Erbil", country: "Iraq" },
  { iata: "IKA", name: "Imam Khomeini", city: "Tehran", country: "Iran" },
  { iata: "JED", name: "King Abdulaziz", city: "Jeddah", country: "Saudi Arabia", keywords: ["Jidda"] },
  { iata: "KWI", name: "Kuwait Intl", city: "Kuwait City", country: "Kuwait" },
  { iata: "MCT", name: "Muscat Intl", city: "Muscat", country: "Oman" },
  { iata: "MED", name: "Prince Mohammad", city: "Medina", country: "Saudi Arabia" },
  { iata: "RUH", name: "King Khalid", city: "Riyadh", country: "Saudi Arabia" },
  { iata: "SHJ", name: "Sharjah Intl", city: "Sharjah", country: "UAE" },
  { iata: "SLL", name: "Salalah Airport", city: "Salalah", country: "Oman" },
  { iata: "TLV", name: "Ben Gurion", city: "Tel Aviv", country: "Israel" },

  // ─── North Africa ─────────────────────────────────────────────
  { iata: "ALG", name: "Houari Boumediene", city: "Algiers", country: "Algeria" },
  { iata: "CAI", name: "Cairo Intl", city: "Cairo", country: "Egypt" },
  { iata: "CMN", name: "Mohammed V", city: "Casablanca", country: "Morocco" },
  { iata: "FEZ", name: "Saïss", city: "Fez", country: "Morocco" },
  { iata: "HRG", name: "Hurghada Intl", city: "Hurghada", country: "Egypt" },
  { iata: "LXR", name: "Luxor Intl", city: "Luxor", country: "Egypt" },
  { iata: "ORN", name: "Ahmed Ben Bella", city: "Oran", country: "Algeria" },
  { iata: "RAK", name: "Menara", city: "Marrakech", country: "Morocco", keywords: ["Marrakesh"] },
  { iata: "RBA", name: "Rabat-Salé", city: "Rabat", country: "Morocco" },
  { iata: "SSH", name: "Sharm el-Sheikh", city: "Sharm el-Sheikh", country: "Egypt" },
  { iata: "TNG", name: "Ibn Battouta", city: "Tangier", country: "Morocco" },
  { iata: "TUN", name: "Tunis-Carthage", city: "Tunis", country: "Tunisia" },

  // ─── Sub-Saharan Africa ───────────────────────────────────────
  { iata: "ABJ", name: "Félix-Houphouët-Boigny", city: "Abidjan", country: "Ivory Coast" },
  { iata: "ABV", name: "Nnamdi Azikiwe", city: "Abuja", country: "Nigeria" },
  { iata: "ACC", name: "Kotoka Intl", city: "Accra", country: "Ghana" },
  { iata: "ADD", name: "Bole Intl", city: "Addis Ababa", country: "Ethiopia" },
  { iata: "BKO", name: "Modibo Keïta", city: "Bamako", country: "Mali" },
  { iata: "BZV", name: "Maya-Maya", city: "Brazzaville", country: "Congo" },
  { iata: "CPT", name: "Cape Town Intl", city: "Cape Town", country: "South Africa" },
  { iata: "DAR", name: "Julius Nyerere", city: "Dar es Salaam", country: "Tanzania" },
  { iata: "DKR", name: "Blaise Diagne", city: "Dakar", country: "Senegal" },
  { iata: "DLA", name: "Douala Intl", city: "Douala", country: "Cameroon" },
  { iata: "DUR", name: "King Shaka", city: "Durban", country: "South Africa" },
  { iata: "EBB", name: "Entebbe Intl", city: "Entebbe", country: "Uganda", keywords: ["Kampala"] },
  { iata: "FIH", name: "N'djili Intl", city: "Kinshasa", country: "DR Congo" },
  { iata: "HRE", name: "Robert Gabriel Mugabe", city: "Harare", country: "Zimbabwe" },
  { iata: "JNB", name: "O.R. Tambo", city: "Johannesburg", country: "South Africa" },
  { iata: "JRO", name: "Kilimanjaro Intl", city: "Arusha", country: "Tanzania", keywords: ["Kilimanjaro"] },
  { iata: "KGL", name: "Kigali Intl", city: "Kigali", country: "Rwanda" },
  { iata: "LLW", name: "Kamuzu Intl", city: "Lilongwe", country: "Malawi" },
  { iata: "LOS", name: "Murtala Muhammed", city: "Lagos", country: "Nigeria" },
  { iata: "LUN", name: "Kenneth Kaunda", city: "Lusaka", country: "Zambia" },
  { iata: "MBA", name: "Moi Intl", city: "Mombasa", country: "Kenya" },
  { iata: "MPM", name: "Maputo Intl", city: "Maputo", country: "Mozambique" },
  { iata: "MRU", name: "Sir Seewoosagur Ramgoolam", city: "Mauritius", country: "Mauritius" },
  { iata: "NBO", name: "Jomo Kenyatta", city: "Nairobi", country: "Kenya" },
  { iata: "RUN", name: "Roland Garros", city: "Saint-Denis", country: "Réunion" },
  { iata: "SEZ", name: "Seychelles Intl", city: "Mahé", country: "Seychelles" },
  { iata: "TNR", name: "Ivato Intl", city: "Antananarivo", country: "Madagascar" },
  { iata: "VFA", name: "Victoria Falls Airport", city: "Victoria Falls", country: "Zimbabwe" },
  { iata: "WDH", name: "Hosea Kutako", city: "Windhoek", country: "Namibia" },
  { iata: "ZNZ", name: "Abeid Amani Karume", city: "Zanzibar", country: "Tanzania" },

  // ─── China ──────────────────────────────────────────────────────
  { iata: "CAN", name: "Baiyun Intl", city: "Guangzhou", country: "China" },
  { iata: "CGO", name: "Xinzheng Intl", city: "Zhengzhou", country: "China" },
  { iata: "CKG", name: "Jiangbei Intl", city: "Chongqing", country: "China" },
  { iata: "CSX", name: "Huanghua Intl", city: "Changsha", country: "China" },
  { iata: "CTU", name: "Tianfu Intl", city: "Chengdu", country: "China" },
  { iata: "DLC", name: "Zhoushuizi", city: "Dalian", country: "China" },
  { iata: "HAK", name: "Meilan Intl", city: "Haikou", country: "China", keywords: ["Hainan"] },
  { iata: "HGH", name: "Xiaoshan Intl", city: "Hangzhou", country: "China" },
  { iata: "HRB", name: "Taiping Intl", city: "Harbin", country: "China" },
  { iata: "KMG", name: "Changshui Intl", city: "Kunming", country: "China", keywords: ["Yunnan"] },
  { iata: "KWL", name: "Liangjiang Intl", city: "Guilin", country: "China", keywords: ["Yangshuo"] },
  { iata: "LJG", name: "Sanyi Intl", city: "Lijiang", country: "China", keywords: ["Yunnan"] },
  { iata: "KWE", name: "Longdongbao Intl", city: "Guiyang", country: "China" },
  { iata: "NKG", name: "Lukou Intl", city: "Nanjing", country: "China" },
  { iata: "NNG", name: "Wuxu Intl", city: "Nanning", country: "China" },
  { iata: "PEK", name: "Capital Intl", city: "Beijing", country: "China" },
  { iata: "PKX", name: "Daxing Intl", city: "Beijing", country: "China" },
  { iata: "PVG", name: "Pudong Intl", city: "Shanghai", country: "China" },
  { iata: "SHA", name: "Hongqiao Intl", city: "Shanghai", country: "China" },
  { iata: "SHE", name: "Taoxian Intl", city: "Shenyang", country: "China" },
  { iata: "SYX", name: "Phoenix Intl", city: "Sanya", country: "China", keywords: ["Hainan"] },
  { iata: "SZX", name: "Bao'an Intl", city: "Shenzhen", country: "China" },
  { iata: "TAO", name: "Jiaodong Intl", city: "Qingdao", country: "China" },
  { iata: "TSN", name: "Binhai Intl", city: "Tianjin", country: "China" },
  { iata: "URC", name: "Diwopu Intl", city: "Ürümqi", country: "China", keywords: ["Xinjiang"] },
  { iata: "WUH", name: "Tianhe Intl", city: "Wuhan", country: "China" },
  { iata: "XIY", name: "Xianyang Intl", city: "Xi'an", country: "China" },
  { iata: "XMN", name: "Gaoqi Intl", city: "Xiamen", country: "China" },

  // ─── Japan ──────────────────────────────────────────────────────
  { iata: "CTS", name: "New Chitose", city: "Sapporo", country: "Japan", keywords: ["Hokkaido"] },
  { iata: "FUK", name: "Fukuoka Airport", city: "Fukuoka", country: "Japan" },
  { iata: "HIJ", name: "Hiroshima Airport", city: "Hiroshima", country: "Japan" },
  { iata: "HND", name: "Haneda", city: "Tokyo", country: "Japan" },
  { iata: "ITM", name: "Itami", city: "Osaka", country: "Japan", keywords: ["Kansai"] },
  { iata: "KIX", name: "Kansai Intl", city: "Osaka", country: "Japan" },
  { iata: "KMJ", name: "Kumamoto Airport", city: "Kumamoto", country: "Japan" },
  { iata: "KOJ", name: "Kagoshima Airport", city: "Kagoshima", country: "Japan" },
  { iata: "NGO", name: "Chubu Centrair", city: "Nagoya", country: "Japan" },
  { iata: "NRT", name: "Narita Intl", city: "Tokyo", country: "Japan" },
  { iata: "OKA", name: "Naha Airport", city: "Okinawa", country: "Japan" },
  { iata: "SDJ", name: "Sendai Airport", city: "Sendai", country: "Japan" },

  // ─── South Korea ────────────────────────────────────────────────
  { iata: "CJU", name: "Jeju Intl", city: "Jeju", country: "South Korea" },
  { iata: "GMP", name: "Gimpo Intl", city: "Seoul", country: "South Korea" },
  { iata: "ICN", name: "Incheon Intl", city: "Seoul", country: "South Korea" },
  { iata: "PUS", name: "Gimhae Intl", city: "Busan", country: "South Korea" },

  // ─── Taiwan, Hong Kong & Macau ──────────────────────────────────
  { iata: "HKG", name: "Hong Kong Intl", city: "Hong Kong", country: "Hong Kong" },
  { iata: "KHH", name: "Kaohsiung Intl", city: "Kaohsiung", country: "Taiwan" },
  { iata: "MFM", name: "Macau Intl", city: "Macau", country: "Macau" },
  { iata: "TPE", name: "Taoyuan Intl", city: "Taipei", country: "Taiwan" },
  { iata: "TSA", name: "Songshan", city: "Taipei", country: "Taiwan" },

  // ─── Mongolia ───────────────────────────────────────────────────
  { iata: "ULN", name: "Chinggis Khaan", city: "Ulaanbaatar", country: "Mongolia" },

  // ─── Southeast Asia ─────────────────────────────────────────────
  { iata: "BKK", name: "Suvarnabhumi", city: "Bangkok", country: "Thailand" },
  { iata: "BKI", name: "Kota Kinabalu Intl", city: "Kota Kinabalu", country: "Malaysia", keywords: ["Borneo", "Sabah"] },
  { iata: "BWN", name: "Brunei Intl", city: "Bandar Seri Begawan", country: "Brunei" },
  { iata: "CEB", name: "Mactan-Cebu", city: "Cebu", country: "Philippines" },
  { iata: "CGK", name: "Soekarno-Hatta", city: "Jakarta", country: "Indonesia" },
  { iata: "CNX", name: "Chiang Mai Intl", city: "Chiang Mai", country: "Thailand" },
  { iata: "CRK", name: "Clark Intl", city: "Clark", country: "Philippines", keywords: ["Manila"] },
  { iata: "CXR", name: "Cam Ranh Intl", city: "Nha Trang", country: "Vietnam" },
  { iata: "DAD", name: "Da Nang Intl", city: "Da Nang", country: "Vietnam" },
  { iata: "DMK", name: "Don Mueang", city: "Bangkok", country: "Thailand" },
  { iata: "DPS", name: "Ngurah Rai", city: "Bali", country: "Indonesia", keywords: ["Denpasar"] },
  { iata: "DVO", name: "Francisco Bangoy", city: "Davao", country: "Philippines", keywords: ["Mindanao"] },
  { iata: "HAN", name: "Noi Bai", city: "Hanoi", country: "Vietnam" },
  { iata: "HKT", name: "Phuket Intl", city: "Phuket", country: "Thailand" },
  { iata: "JOG", name: "Adisucipto Intl", city: "Yogyakarta", country: "Indonesia", keywords: ["Borobudur"] },
  { iata: "KCH", name: "Kuching Intl", city: "Kuching", country: "Malaysia", keywords: ["Borneo", "Sarawak"] },
  { iata: "KBV", name: "Krabi Airport", city: "Krabi", country: "Thailand" },
  { iata: "KLO", name: "Kalibo Intl", city: "Kalibo", country: "Philippines", keywords: ["Boracay"] },
  { iata: "KUL", name: "Kuala Lumpur Intl", city: "Kuala Lumpur", country: "Malaysia" },
  { iata: "LGK", name: "Langkawi Intl", city: "Langkawi", country: "Malaysia" },
  { iata: "LPQ", name: "Luang Prabang Intl", city: "Luang Prabang", country: "Laos" },
  { iata: "MNL", name: "Ninoy Aquino", city: "Manila", country: "Philippines" },
  { iata: "PEN", name: "Penang Intl", city: "Penang", country: "Malaysia", keywords: ["George Town"] },
  { iata: "PNH", name: "Phnom Penh Intl", city: "Phnom Penh", country: "Cambodia" },
  { iata: "PQC", name: "Phu Quoc Intl", city: "Phu Quoc", country: "Vietnam" },
  { iata: "REP", name: "Siem Reap Intl", city: "Siem Reap", country: "Cambodia", keywords: ["Angkor Wat"] },
  { iata: "RGN", name: "Yangon Intl", city: "Yangon", country: "Myanmar", keywords: ["Rangoon"] },
  { iata: "SGN", name: "Tan Son Nhat", city: "Ho Chi Minh City", country: "Vietnam", keywords: ["Saigon"] },
  { iata: "SIN", name: "Changi", city: "Singapore", country: "Singapore" },
  { iata: "SUB", name: "Juanda Intl", city: "Surabaya", country: "Indonesia" },
  { iata: "USM", name: "Koh Samui Airport", city: "Koh Samui", country: "Thailand" },
  { iata: "VTE", name: "Wattay Intl", city: "Vientiane", country: "Laos" },

  // ─── South Asia ─────────────────────────────────────────────────
  { iata: "AMD", name: "Sardar Vallabhbhai Patel", city: "Ahmedabad", country: "India" },
  { iata: "BLR", name: "Kempegowda Intl", city: "Bangalore", country: "India", keywords: ["Bengaluru"] },
  { iata: "BOM", name: "Chhatrapati Shivaji", city: "Mumbai", country: "India", keywords: ["Bombay"] },
  { iata: "CCU", name: "Netaji Subhas Chandra Bose", city: "Kolkata", country: "India", keywords: ["Calcutta"] },
  { iata: "CJB", name: "Coimbatore Intl", city: "Coimbatore", country: "India" },
  { iata: "CMB", name: "Bandaranaike", city: "Colombo", country: "Sri Lanka" },
  { iata: "COK", name: "Cochin Intl", city: "Kochi", country: "India", keywords: ["Cochin", "Kerala"] },
  { iata: "DAC", name: "Hazrat Shahjalal", city: "Dhaka", country: "Bangladesh" },
  { iata: "DEL", name: "Indira Gandhi", city: "Delhi", country: "India", keywords: ["New Delhi"] },
  { iata: "GAU", name: "Lokpriya Gopinath Bordoloi", city: "Guwahati", country: "India", keywords: ["Assam"] },
  { iata: "GOI", name: "Dabolim Airport", city: "Goa", country: "India" },
  { iata: "HYD", name: "Rajiv Gandhi Intl", city: "Hyderabad", country: "India" },
  { iata: "IDR", name: "Devi Ahilyabai Holkar", city: "Indore", country: "India" },
  { iata: "ISB", name: "Islamabad Intl", city: "Islamabad", country: "Pakistan" },
  { iata: "JAI", name: "Jaipur Intl", city: "Jaipur", country: "India", keywords: ["Rajasthan"] },
  { iata: "KHI", name: "Jinnah Intl", city: "Karachi", country: "Pakistan" },
  { iata: "KTM", name: "Tribhuvan Intl", city: "Kathmandu", country: "Nepal" },
  { iata: "LHE", name: "Allama Iqbal", city: "Lahore", country: "Pakistan" },
  { iata: "LKO", name: "Chaudhary Charan Singh", city: "Lucknow", country: "India" },
  { iata: "MAA", name: "Chennai Intl", city: "Chennai", country: "India", keywords: ["Madras"] },
  { iata: "MLE", name: "Velana Intl", city: "Malé", country: "Maldives", keywords: ["Maldives"] },
  { iata: "NAG", name: "Dr. Babasaheb Ambedkar", city: "Nagpur", country: "India" },
  { iata: "PNQ", name: "Pune Airport", city: "Pune", country: "India" },
  { iata: "SXR", name: "Sheikh ul-Alam", city: "Srinagar", country: "India", keywords: ["Kashmir"] },
  { iata: "TRV", name: "Thiruvananthapuram Intl", city: "Thiruvananthapuram", country: "India", keywords: ["Trivandrum", "Kerala"] },
  { iata: "VNS", name: "Lal Bahadur Shastri", city: "Varanasi", country: "India" },

  // ─── Oceania ────────────────────────────────────────────────────
  { iata: "ADL", name: "Adelaide Airport", city: "Adelaide", country: "Australia" },
  { iata: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand" },
  { iata: "APW", name: "Faleolo Intl", city: "Apia", country: "Samoa" },
  { iata: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "Australia" },
  { iata: "CBR", name: "Canberra Airport", city: "Canberra", country: "Australia" },
  { iata: "CHC", name: "Christchurch Airport", city: "Christchurch", country: "New Zealand" },
  { iata: "CNS", name: "Cairns Airport", city: "Cairns", country: "Australia" },
  { iata: "DRW", name: "Darwin Intl", city: "Darwin", country: "Australia" },
  { iata: "DUD", name: "Dunedin Airport", city: "Dunedin", country: "New Zealand" },
  { iata: "GUM", name: "Antonio B. Won Pat", city: "Hagåtña", country: "Guam" },
  { iata: "HBA", name: "Hobart Airport", city: "Hobart", country: "Australia", keywords: ["Tasmania"] },
  { iata: "MEL", name: "Tullamarine", city: "Melbourne", country: "Australia" },
  { iata: "NAN", name: "Nadi Intl", city: "Nadi", country: "Fiji" },
  { iata: "NOU", name: "La Tontouta", city: "Nouméa", country: "New Caledonia" },
  { iata: "OOL", name: "Gold Coast Airport", city: "Gold Coast", country: "Australia", keywords: ["Coolangatta"] },
  { iata: "PER", name: "Perth Airport", city: "Perth", country: "Australia" },
  { iata: "POM", name: "Jacksons Intl", city: "Port Moresby", country: "Papua New Guinea" },
  { iata: "PPT", name: "Faa'a Intl", city: "Papeete", country: "French Polynesia", keywords: ["Tahiti"] },
  { iata: "RAR", name: "Rarotonga Intl", city: "Rarotonga", country: "Cook Islands" },
  { iata: "SYD", name: "Kingsford Smith", city: "Sydney", country: "Australia" },
  { iata: "TBU", name: "Fuaʻamotu Intl", city: "Nukuʻalofa", country: "Tonga" },
  { iata: "WLG", name: "Wellington Airport", city: "Wellington", country: "New Zealand" },
  { iata: "ZQN", name: "Queenstown Airport", city: "Queenstown", country: "New Zealand" },
] as const

/** O(1) lookup by IATA code. */
export const AIRPORT_BY_IATA: ReadonlyMap<string, Airport> = new Map(
  AIRPORTS.map(a => [a.iata, a]),
)
